import React from 'react'
import { storiesOf } from '@storybook/react'

import VHFixedBar from '.'

storiesOf('Components/FixedBar/template1', module)

.add('Show fixed bar', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar>
            New Vanhack Component Created
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))

.add('Show fixed bar size2', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar size2>
            New Vanhack Component Created
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))

.add('Show fixed bar size3', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar size3>
            New Vanhack Component Created
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))

.add('Show fixed bar size4', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar size4>
            New Vanhack Component Created
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))
storiesOf('Components/FixedBar/template2', module)

.add('Show fixed bar', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar template2>
            New Vanhack Component Created
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))

.add('Show fixed bar size2', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar template2 size2>
            New Vanhack Component Created
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))

.add('Show fixed bar size3', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar template2 size3>
            New Vanhack Component Created
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))

.add('Show fixed bar size4', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar template2 size4>
            New Vanhack Component Created
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))
