import React from 'react'
import { storiesOf } from '@storybook/react'

import VHFixedBar from '.'

storiesOf('Components/FixedBar', module)

.add('Show fixed bar', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar show>
            New Vanhack Component Created
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))

.add('Show fixed bar template2', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar show template2>
            New Vanhack Component Created
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))

.add('Show fixed bar template3', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar show template3>
            New Vanhack Component Created
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))

.add('Show fixed bar template4', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar show template4>
            New Vanhack Component Created
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))

.add('No Show fixed bar', () => (
    <div style={{background: "silver"}}>
        <VHFixedBar>
            New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />New Vanhack Component Created <br />
        </VHFixedBar>
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
        Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />Component <br />
    </div>
))

